no message

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -68,6 +68,73 @@ jobs:
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
           xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=iPhone 16"
 
+#      - name: Generate diff images for all failed snapshots using ksdiff
+#        if: failure()
+#        run: |
+#          set -e
+#          FAILED_DIR="./citest02/Snapshots/__Snapshots__/Failure/SnapshotFilePath"
+#          SUCCESS_DIR="./citest02/Snapshots/__Snapshots__/SnapshotFilePath"
+#          DIFF_DIR="$(pwd)/artifacts/diffs"
+#          mkdir -p "$DIFF_DIR"
+#      
+#          for failed in "$FAILED_DIR"/*; do
+#            filename=$(basename "$failed")
+#            success="$SUCCESS_DIR/$filename"
+#            if [ -f "$success" ]; then
+#              diff_file="$DIFF_DIR/diff_$filename"
+#              echo "Generating diff for $filename"
+#              echo "before: compare"
+#              output=$(compare "$success" "$failed" "$diff_file" 2>&1) || true
+#              exit_code=$?
+#              echo "after compare"
+#              if [ $exit_code -ne 0 ] && [ ! -f "$diff_file" ]; then
+#                echo "Error while comparing $filename:"
+#                echo "$output"
+#                exit 1
+#              else
+#                echo "Success: $diff_file"
+#              fi
+#            else
+#              echo "Success snapshot not found for $filename, skipping."
+#            fi
+#          done
+#
+#      - name: Encode images and output
+#        if: failure()
+#        id: encode_diff_images
+#        run: |
+#          delimiter=$(openssl rand -hex 8)
+#          if ls ./artifacts/diffs/*.png >/dev/null 2>&1; then
+#            {
+#              echo "ENCODED_IMAGES<<$delimiter"
+#              for file in ./artifacts/diffs/*.png; do
+#                encoded=$(base64 -i "$file")
+#                echo "![Diff Image $(basename "$file")](data:image/png;base64,$encoded)"
+#                echo ""
+#              done
+#              echo "$delimiter"
+#            } >> "$GITHUB_OUTPUT"
+#          else
+#            echo "ENCODED_IMAGES=" >> "$GITHUB_OUTPUT"
+#          fi
+#
+#      - name: Comment on PR with snapshot diffs
+#        if: failure() && steps.encode_diff_images.outputs.ENCODED_IMAGES != ''
+#        uses: marocchino/sticky-pull-request-comment@v2
+#        with:
+#          message: |
+#            🚨 **Snapshotテストで差分が発生しています** 🚨
+#      
+#            ${{ steps.encode_diff_images.outputs.ENCODED_IMAGES }}
+
+      # 生成した複数のdiff画像をアーティファクトとしてアップロード
+#      - name: Upload diff artifacts
+#        if: failure()
+#        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+#        with:
+#          name: snapshot-diff
+#          path: artifacts/diffs
+
       - name: Generate diff images for all failed snapshots using ksdiff
         if: failure()
         run: |
@@ -82,58 +149,27 @@ jobs:
             success="$SUCCESS_DIR/$filename"
             if [ -f "$success" ]; then
               diff_file="$DIFF_DIR/diff_$filename"
-              echo "Generating diff for $filename"
-              echo "before: compare"
-              output=$(compare "$success" "$failed" "$diff_file" 2>&1) || true
-              exit_code=$?
-              echo "after compare"
-              if [ $exit_code -ne 0 ] && [ ! -f "$diff_file" ]; then
-                echo "Error while comparing $filename:"
-                echo "$output"
-                exit 1
-              else
-                echo "Success: $diff_file"
-              fi
-            else
-              echo "Success snapshot not found for $filename, skipping."
+              compare "$success" "$failed" "$diff_file" || true
             fi
           done
 
-      - name: Encode images and output
+      - name: Upload diff images as Artifact
         if: failure()
-        id: encode_diff_images
-        run: |
-          delimiter=$(openssl rand -hex 8)
-          if ls ./artifacts/diffs/*.png >/dev/null 2>&1; then
-            {
-              echo "ENCODED_IMAGES<<$delimiter"
-              for file in ./artifacts/diffs/*.png; do
-                encoded=$(base64 -i "$file")
-                echo "![Diff Image $(basename "$file")](data:image/png;base64,$encoded)"
-                echo ""
-              done
-              echo "$delimiter"
-            } >> "$GITHUB_OUTPUT"
-          else
-            echo "ENCODED_IMAGES=" >> "$GITHUB_OUTPUT"
-          fi
+        uses: actions/upload-artifact@v4
+        with:
+          name: snapshot-diffs
+          path: artifacts/diffs/*.png
 
-      - name: Comment on PR with snapshot diffs
-        if: failure() && steps.encode_diff_images.outputs.ENCODED_IMAGES != ''
+      - name: Comment on PR with link to Artifact
+        if: failure()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
+          GITHUB_TOKEN: ${{ secrets.MY_PAT }} # PATを使用
           message: |
             🚨 **Snapshotテストで差分が発生しています** 🚨
       
-            ${{ steps.encode_diff_images.outputs.ENCODED_IMAGES }}
+            差分画像は[こちらのArtifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)からダウンロードできます。
 
-      # 生成した複数のdiff画像をアーティファクトとしてアップロード
-      - name: Upload diff artifacts
-        if: failure()
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
-        with:
-          name: snapshot-diff
-          path: artifacts/diffs
 
       - name: Cache VRT snapshots
         if: always()
